include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.mocks.dart"
    - "**/core/localization/generated/**"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Ưu tiên sử dụng early return: Nếu không có else, hãy kiểm tra điều kiện ngược và return sớm để code rõ ràng, tránh lồng if.
    avoid_print: true
    prefer_single_quotes: true
    avoid_function_literals_in_foreach_calls: false
    always_declare_return_types: true
    unnecessary_new: true
    avoid_empty_else: true
    directives_ordering: true
    avoid_unused_constructor_parameters: true
    prefer_relative_imports: true
    curly_braces_in_flow_control_structures: true
    constant_identifier_names: true
    empty_catches: true
    depend_on_referenced_packages: true
    use_key_in_widget_constructors: true
    require_trailing_commas: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true
    no_duplicate_case_values: true
    sort_constructors_first: true
    no_leading_underscores_for_local_identifiers: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: false
    prefer_final_parameters: false
    prefer_const_declarations: true
    avoid_returning_null_for_void: false
    avoid_return_types_on_setters: true
    avoid_positional_boolean_parameters: false
    prefer_expression_function_bodies: false
    avoid_redundant_argument_values: false
